'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4200
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.3038.
'

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"), _
     System.Web.Services.WebServiceAttribute([Namespace]:="http://developer.intuit.com/"), _
     System.Web.Services.WebServiceBindingAttribute(Name:="QBWebConnectorSvcSoap", [Namespace]:="http://developer.intuit.com/")> _
    Partial Public MustInherit Class QBWebConnectorSvc
        Inherits System.Web.Services.WebService

        '''<remarks/>
        <System.Web.Services.WebMethodAttribute(), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://developer.intuit.com/authenticate", RequestNamespace:="http://developer.intuit.com/", ResponseNamespace:="http://developer.intuit.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public MustOverride Function authenticate(ByVal strUserName As String, ByVal strPassword As String) As String()

        '''<remarks/>
        <System.Web.Services.WebMethodAttribute(), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://developer.intuit.com/sendRequestXML", RequestNamespace:="http://developer.intuit.com/", ResponseNamespace:="http://developer.intuit.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public MustOverride Function sendRequestXML(ByVal ticket As String, ByVal strHCPResponse As String, ByVal strCompanyFileName As String, ByVal qbXMLCountry As String, ByVal qbXMLMajorVers As Integer, ByVal qbXMLMinorVers As Integer) As String

        '''<remarks/>
        <System.Web.Services.WebMethodAttribute(), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://developer.intuit.com/receiveResponseXML", RequestNamespace:="http://developer.intuit.com/", ResponseNamespace:="http://developer.intuit.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public MustOverride Function receiveResponseXML(ByVal ticket As String, ByVal response As String, ByVal hresult As String, ByVal message As String) As Integer

        '''<remarks/>
        <System.Web.Services.WebMethodAttribute(), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://developer.intuit.com/connectionError", RequestNamespace:="http://developer.intuit.com/", ResponseNamespace:="http://developer.intuit.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public MustOverride Function connectionError(ByVal ticket As String, ByVal hresult As String, ByVal message As String) As String

        '''<remarks/>
        <System.Web.Services.WebMethodAttribute(), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://developer.intuit.com/getLastError", RequestNamespace:="http://developer.intuit.com/", ResponseNamespace:="http://developer.intuit.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public MustOverride Function getLastError(ByVal ticket As String) As String

        '''<remarks/>
        <System.Web.Services.WebMethodAttribute(), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://developer.intuit.com/closeConnection", RequestNamespace:="http://developer.intuit.com/", ResponseNamespace:="http://developer.intuit.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public MustOverride Function closeConnection(ByVal ticket As String) As String
    End Class